# Generated by Django 4.2.6 on 2023-10-13 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_files_column_names_files_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='column_names',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
